refactor: major overhaul and cleanup of the build environment
- Removed `.env.sample` and improved `.env` handling
- Deleted `translate.py` and replaced it with `translate-md.py`
- Refactored `readme.yml` to enhance translation and tagging workflow
- Updated `.gitignore` with new exclusions
- Major restructuring of `Dockerfile`, including improved ENV variables and layout
- Extended `create-env.sh` with interactive prompts and validation
- Improved error handling and structure in `docker-compose-wrapper`
- Expanded `docker-compose.yml` with new environment variables and network settings
- Moved and updated `init.sh`, `.bashrc`, and other files to `files/` directory
- Added new scripts: `show-env.sh` for better diagnostics and `terminal-splash.txt` for enhanced display

These changes optimize the build environment for improved stability and flexibility.

diff --git a/docker-compose-wrapper b/docker-compose-wrapper
--- a/docker-compose-wrapper
+++ b/docker-compose-wrapper
@@ -1,16 +1,28 @@
 #!/bin/bash
 
-# Path to script that will be executed before starts docker-compose
+# Path to script that will be executed before starting docker-compose
 ENV_SCRIPT="./create-env.sh"
+
+# Define exit codes as constants
+EXIT_USER_CANCEL=70
 
 # Check script
 if [ -x "$ENV_SCRIPT" ]; then
-    echo "executing $ENV_SCRIPT..."
-    $ENV_SCRIPT
+    echo "Executing $ENV_SCRIPT..."
+    "$ENV_SCRIPT"
+    EXIT_CODE=$?
+    
+    if [ $EXIT_CODE -eq $EXIT_USER_CANCEL ]; then
+        echo "create-env.sh was canceled by the user."
+        exit $EXIT_USER_CANCEL
+    elif [ $EXIT_CODE -ne 0 ]; then
+        echo "create-env.sh failed with exit code $EXIT_CODE."
+        exit $EXIT_CODE
+    fi
 else
     echo "Error: $ENV_SCRIPT not found or not executable."
     exit 1
 fi
 
-# Execute docker-compose with all parameters an sub commannds
+# Execute docker-compose with all parameters and subcommands
 docker-compose "$@"
